### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ja-martinez** [ASU-CompMethodsPhysics-PHY494/final-march-madness#2]
@orbeckst @ianmkenney I have created a wiki page has a more specific direction of the project. Could you please check it and tell me is it is headed in the right direction?

**Comment by orbeckst** [comment]
Yes, your wiki looks good.
In general, I would start with very simple parameters, get a "toy system" running, and then come back and refine how to decide who wins.
You could start with just assigning a random "strength" value to each team (say, number between 0 and 10) and then say that the probability that team A with strength S_A wins against team B is 

```
P(A wins) = S_A/(S_A + S_B)
```

I very much encourage you to do "rapid prototyping", i.e. get something small working and then improve upon the working prototype instead of trying to set up everything perfectly in the beginning. Quick and dirty is better than slow and elaborate.

**Comment by ja-martinez** [comment]
Thank you for your suggestion, Professor. We will start up simple and build it from there.

@bkatterm
